apiVersion: v1
kind: Service
metadata:
  name: {{ include "bpdm.fullname" . }}
  labels:
    {{- include "bpdm.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: catenax-bpdm-dev
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "bpdm.selectorLabels" . | nindent 4 }}
