# Default values for k8s-helm-example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: ftcpro.azurecr.io
  repository: bpdm/pool
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: [ ]

podAnnotations: { }

#Spring profiles under which the application should run
springProfiles:
  - dev

# Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
# @url: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 3000
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8080

autoscaling:
  enabled: false

ingress:
  className: nginx
  createRootPath: false
  subPath: /v2
  hosts:
    - partners-pool.dev.demo.ftcpro.co

# Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
# @url: https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-resource-requests-and-limits
resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 500Mi

nodeSelector: { }

tolerations: [ ]

# Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
# @url: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: DoesNotExist
          topologyKey: kubernetes.io/hostname

# Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
# @url: https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L210
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

applicationSecret:
  enabled: true
  keycloak: <path:bpdm/data/dev/pool/keycloak#credentials-secret>
  cdq: <path:bpdm/data/dev/pool/cdq#api-key>

applicationConfig: # |
  # property=value

opensearch:
  host: opensearch-cluster-master.opensearch
  enabled: false


postgres:
  enabled: false
  auth:
    database: bpdm
    postgresPassword: <path:bpdm/data/dev/pool/postgresql#postgres-password>
    username: bpdm
    password: <path:bpdm/data/dev/pool/postgresql#password>
    host: ftcpro-postgresql-primary.postgres

