springProfiles:
  - int

ingress:
  hosts:
    - partners-pool.demo.catena-x.net

applicationSecret:
  keycloak: <path:bpdm/data/int/pool/keycloak#credentials-secret>
  cdq: <path:bpdm/data/int/pool/cdq#api-key>

postgres:
  auth:
    postgresPassword: <path:bpdm/data/int/pool/postgresql#postgres-password>
    password: <path:bpdm/data/int/pool/postgresql#password>