apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bpdm.fullname" . }}
  labels:
     {{- include "bpdm.labels" . | nindent 4 }}
data:
  external.properties: |-
    # External properties for overwriting application config
    {{- if .Values.applicationConfig }}
    {{- .Values.applicationConfig | nindent 4 }}
    {{- end }}