name: Test on opened pull request
on:
  pull_request:
    types: [opened, reopened]

jobs:
  test-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots verify