name: Full Vera Code Scan

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
  schedule:
    # Once a day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      #Setup Java 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      #Create/Get Maven package cache
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      #Package application with Maven
      - name: Package to JAR
        run: ./mvnw -B package

      #Start Veracode scan
      - name: Run Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          appname: "BPDM - Business Partner Data Management"
          createprofile: false
          filepath: "target/bpdm.jar"
          vid: "${{ secrets.VERACODE_API_ID }}"
          vkey: "${{ secrets.VERACODE_API_KEY }}"